// <auto-generated />
using AssetNode.Services.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetNode.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20250826052445_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetNode.Models.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentAssetId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetNode.Models.Entities.Asset", b =>
                {
                    b.HasOne("AssetNode.Models.Entities.Asset", "ParentAsset")
                        .WithMany("Children")
                        .HasForeignKey("ParentAssetId");

                    b.Navigation("ParentAsset");
                });

            modelBuilder.Entity("AssetNode.Models.Entities.Asset", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
